---
# Dock items to remove.
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Books
  - Maps
  - Contacts
  - Freeform
  - Music
  - News
  - 'IPhone Mirroring'
  - FaceTime

# Dock items to add. `pos` parameter is optional and will place the Dock item
# in a particular position in the Dock.
dockitems_persist:
  - name: "Raycast"
    path: "/Applications/Raycast.app/"
    pos: 5
  - name: "Warp"
    path: "/Applications/Warp.app/"
    pos: 10
  - name: "Chrome"
    path: "/Applications/Google\ Chrome.app/"
    pos: 11
  - name: "Teams"
    path: "/Applications/Microsoft\ Teams.app/"
    pos: 12

# Whether to install dockutil or not
dockutil_install: true
