---
- name: Install dockutil.
  community.general.homebrew:
    name: dockutil
    state: present
  notify:
    - Clear homebrew cache
  when: dockutil_install
  tags: ['dock']

- name: Remove configured Dock items.
  ansible.builtin.include_tasks: dock-remove.yml
  loop: "{{ dockitems_remove }}"
  loop_control:
    extended: true
    extended_allitems: false
  tags: ['dock']

- name: Ensure required dock items exist.
  ansible.builtin.include_tasks: dock-add.yml
  loop: "{{ dockitems_persist }}"
  loop_control:
    extended: true
    extended_allitems: false
  tags: ['dock']

- name: Ensure dock items are in correct position.
  ansible.builtin.include_tasks: dock-position.yml
  when:
    - item.pos is defined
    - item.pos > 0
  loop: "{{ dockitems_persist }}"
  loop_control:
    extended: true
    extended_allitems: false
  tags: ['dock']

- name: Turn off suggestions,minimize,folders
  ansible.builtin.shell: |
    defaults write com.apple.dock show-recents -bool false
    defaults write com.apple.dock minimize-to-application -bool YES
    defaults write com.apple.dock persistent-others -array
    defaults write com.apple.dock tilesize -int 50; killall Dock
