---    
- name: Template Brewfile
  ansible.builtin.template:
    src: Brewfile.j2
    dest: /opt/homebrew/Brewfile
    owner: muzcee
    group: admin
    mode: '0644'

- name: Install from Brewfile.
  command: "/opt/homebrew/bin/brew bundle"
  args:
    chdir: /opt/homebrew/

- name: Cleanup from Brewfile.
  command: "/opt/homebrew/bin/brew bundle --force cleanup"
  args:
    chdir: /opt/homebrew/
