---
brew_packages:
  - ansible
  - ansible-lint
  - brotli
  - btop
  - ca-certificates
  - certifi
  - cffi
  - cmake
  - cryptography
  - curl
  - docker
  - docker-completion
  - dockutil
  - fzf
  - gettext
  - gh
  - iperf3
  - libnghttp2
  - libnghttp3
  - libngtcp2
  - libsodium
  - libssh
  - libssh2
  - libtool
  - libunistring
  - libuv
  - libyaml
  - lpeg
  - lsd
  - luajit
  - luv
  - lz4
  - m4
  - mas
  - mpdecimal
  - neofetch
  - neovim
  - openssl@3
  - pcre2
  - pkgconf
  - pycparser
  - python@3.14
  - readline
  - ripgrep
  - rpds-py
  - rtmpdump
  - screenresolution
  - sqlite
  - starship
  - tree
  - tree-sitter@0.25
  - unibilium
  - unzip
  - utf8proc
  - xz
  - yazi
  - zstd
  - bat
brew_casks:
  - docker-desktop
  - font-droid-sans-mono-nerd-font
  - google-chrome
  - microsoft-teams
  - raycast
  - tailscale-app
  - warp


